### ISSUE TITLE
densebox 用的什么数据集

### ISSUE THREAD

**Issue by jeannotes** [kyn0v/ObjectDetection#1]
你好，问一下，densebox 用的什么数据集，现在训练成功了吗？

**Comment by kyn0v** [comment]
你好，我的项目是fork：https://github.com/CaptainEven/DenseBox这个仓库的，有少量改写。数据集是车牌数据集(无landmark)，原作者在README里有分享。我改写后的版本训练成功了。

**Comment by kyn0v** [comment]
你好，我的项目是fork：https://github.com/CaptainEven/DenseBox 这个仓库的，有少量改写。数据集是车牌数据集(无landmark)，原作者在README里有分享。我改写后的版本训练成功了。
